config/routes.rb
Rails.application.routes.draw do


  root :to => 'welcome#index'


  get '/institutional-partners' => 'welcome#institutional_partners'
  get '/custom-products' => 'welcome#custom_products'
  get '/fx-products' => 'welcome#fx_products'
  get '/corporate-ethics' => 'welcome#corporate_ethics'
  get '/intro-to-pi' => 'welcome#intro_to_pi'

  # Seat reservation views
  get '/login' => 'seat_reservation#login'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/seat_reservation_controller.rb
class SeatReservationController < ApplicationController
  def login

      render :login
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

      render :index
  end

  def institutional_partners


      render :institutional_partners, layout: 'company'
  end
  def custom_products


      render :custom_products, layout: 'company'
  end
  def fx_products


      render :fx_products, layout: 'company'
  end
  def corporate_ethics


      render :corporate_ethics, layout: 'company'
  end
  def intro_to_pi


      render :intro_to_pi, layout: 'company'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/seat_reservation_helper.rb
module SeatReservationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VinquloApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900,900i&subset=latin-ext" rel="stylesheet">
  </head>

  <nav class="navbar navbar-default vinqulo-navbar">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-2">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">
              <%= image_tag('vinqulo-logo.png', :alt => 'Vinqulo', :class => 'img-responsive vinqulo-logo') %>
          </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar-collapse-2">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'Institutional Partners', institutional_partners_path %></li>
            <li><%= link_to 'Custom Products', custom_products_path %></li>
            <li><%= link_to 'FX Products', fx_products_path %></li>
            <li><%= link_to 'Corporate Ethics', corporate_ethics_path %></li>
            <li><%= link_to 'Intro to PI', intro_to_pi_path %></li>
            <li>
              <!-- <a class="btn btn-default btn-outline btn-circle collapsed vinqulo-login"  data-toggle="collapse" href="#nav-collapse2" aria-expanded="false" aria-controls="nav-collapse2">Login</a> -->
              <%= link_to 'Login', login_path, :class => 'btn btn-default btn-outline btn-circle vinqulo-login' %>
            </li>
          </ul>
          <div class="collapse nav navbar-nav nav-collapse slide-down" id="nav-collapse2">
            <form class="navbar-form navbar-right form-inline" role="form">
              <div class="form-group">
                <label class="sr-only" for="Email">Email</label>
                <input type="email" class="form-control" id="Email" placeholder="Email" autofocus required />
              </div>
              <div class="form-group">
                <label class="sr-only" for="Password">Password</label>
                <input type="password" class="form-control" id="Password" placeholder="Password" required />
              </div>
              <button type="submit" class="btn btn-success">Sign in</button>
            </form>
          </div>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->
    </nav><!-- /.navbar -->

  <body>
    <%= yield %>


  <section class="footer">
      <div class="container">
          <div class="col-lg-10 about-text">
              <div class="col-md-8 testimonial">
                  <div class="face-cont col-sm-2 hidden-xs">
                      <span class="face face2"></span>
                  </div>
                  <blockquote class="col-md-10 col-md-push-1">
                      <p>
                          The software has been a proven winner.
                      </p>
                      <cite>Don Hutchings, Investor</cite>
                  </blockquote>
              </div>
              <ul class="col-lg-4 col-md-push-2 social">
                  <li><%= link_to 'Institutional Partners', institutional_partners_path %></li>
                  <li><%= link_to 'Custom Products', custom_products_path %></li>
                  <li><%= link_to 'FX Products', fx_products_path %></li>
                  <li><%= link_to 'Corporate Ethics', corporate_ethics_path %></li>
                  <li><%= link_to 'Intro to PI', intro_to_pi_path %></li>
                  <li><a href="mailto:abratten@mac.com">Contact Us</a></li>
              </ul>
          </div>
      </div>
  </section>

  <section id="copyright">
      <div class="container">
          <div class="col-lg-12 col-sm-12 row" id="copy">
              <span class="col-md-5">© 2016 Vinqulo, Inc</span>
          </div>
      </div>
  </section>






  <!-- Header Video Modal -->
  <div class="modal fade" id="videoModal" tabindex="-1" role="dialog" aria-labelledby="videoModal" aria-hidden="true">
      <div class="modal-dialog">
          <div class="modal-content">
              <div class="modal-body">
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                  <div>
                      <iframe width="100%" height="350" src=""></iframe>
                  </div>
              </div>
          </div>
      </div>
  </div>


  <!-- jQuery for Video Modal -->
  <script>
      autoPlayYouTubeModal();

      //FUNCTION TO GET AND AUTO PLAY YOUTUBE VIDEO FROM DATATAG
      function autoPlayYouTubeModal() {
          var trigger = $("body").find('[data-toggle="modal"]');
          trigger.click(function () {
              var theModal = $(this).data("target"),
                  videoSRC = $(this).attr("data-theVideo"),
                  videoSRCauto = videoSRC + "?autoplay=1";
              $(theModal + ' iframe').attr('src', videoSRCauto);
              $(theModal + ' button.close').click(function () {
                  $(theModal + ' iframe').attr('src', videoSRC);
              });
          });
      }
  </script>

  </body>
</html>

app/views/layouts/company.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VinquloApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900,900i&subset=latin-ext" rel="stylesheet">
  </head>

  <nav class="navbar navbar-default vinqulo-navbar">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-2">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">
              <%= image_tag('vinqulo-logo.png', :alt => 'Vinqulo', :class => 'img-responsive vinqulo-logo') %>
          </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar-collapse-2">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'Institutional Partners', institutional_partners_path %></li>
            <li><%= link_to 'Custom Products', custom_products_path %></li>
            <li><%= link_to 'FX Products', fx_products_path %></li>
            <li><%= link_to 'Corporate Ethics', corporate_ethics_path %></li>
            <li><%= link_to 'Intro to PI', intro_to_pi_path %></li>
            <li>
              <!-- <a class="btn btn-default btn-outline btn-circle collapsed vinqulo-login"  data-toggle="collapse" href="#nav-collapse2" aria-expanded="false" aria-controls="nav-collapse2">Login</a> -->
              <%= link_to 'Login', login_path, :class => 'btn btn-default btn-outline btn-circle vinqulo-login' %>
            </li>
          </ul>
          <div class="collapse nav navbar-nav nav-collapse slide-down" id="nav-collapse2">
            <form class="navbar-form navbar-right form-inline" role="form">
              <div class="form-group">
                <label class="sr-only" for="Email">Email</label>
                <input type="email" class="form-control" id="Email" placeholder="Email" autofocus required />
              </div>
              <div class="form-group">
                <label class="sr-only" for="Password">Password</label>
                <input type="password" class="form-control" id="Password" placeholder="Password" required />
              </div>
              <button type="submit" class="btn btn-success">Sign in</button>
            </form>
          </div>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->
    </nav><!-- /.navbar -->

  <body>

      <section id="about_us">
          <div class="container">
          	<div class="row">
    			<div class="col-md-3" id="leftCol">



        		</div>

                <%= yield %>

            </div>
          </div>
      </section>


  <section class="footer">
      <div class="container">
          <div class="col-lg-10 about-text">
              <div class="col-lg-8">
                  Butcher beard gentrify, taxidermy literally kitsch XOXO vice. Venmo vice craft beer direct trade, readymade 8-bit actually synth mixtape poutine truffaut blog drinking vinegar. Kombucha tacos poutine, gochujang bespoke ugh iPhone. Messenger bag dreamcatcher brooklyn occupy, migas typewriter drinking vinegar church-key.
              </div>
              <ul class="col-lg-4 pull-right social">
                  <li><%= link_to 'Institutional Partners', institutional_partners_path %></li>
                  <li><%= link_to 'Custom Products', custom_products_path %></li>
                  <li><%= link_to 'FX Products', fx_products_path %></li>
                  <li><%= link_to 'Corporate Ethics', corporate_ethics_path %></li>
                  <li><%= link_to 'Intro to PI', intro_to_pi_path %></li>
                  <li><a href="mailto:abratten@mac.com">Contact Us</a></li>
              </ul>
          </div>
      </div>
  </section>

  <section id="copyright">
      <div class="container">
          <div class="col-lg-12 col-sm-12 row" id="copy">
              <span class="col-md-5">© 2016 Vinqulo, Inc</span>
          </div>
      </div>
  </section>






  <!-- Header Video Modal -->
  <div class="modal fade" id="videoModal" tabindex="-1" role="dialog" aria-labelledby="videoModal" aria-hidden="true">
      <div class="modal-dialog">
          <div class="modal-content">
              <div class="modal-body">
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                  <div>
                      <iframe width="100%" height="350" src=""></iframe>
                  </div>
              </div>
          </div>
      </div>
  </div>


  <!-- jQuery for Video Modal -->
  <script>
      autoPlayYouTubeModal();

      //FUNCTION TO GET AND AUTO PLAY YOUTUBE VIDEO FROM DATATAG
      function autoPlayYouTubeModal() {
          var trigger = $("body").find('[data-toggle="modal"]');
          trigger.click(function () {
              var theModal = $(this).data("target"),
                  videoSRC = $(this).attr("data-theVideo"),
                  videoSRCauto = videoSRC + "?autoplay=1";
              $(theModal + ' iframe').attr('src', videoSRCauto);
              $(theModal + ' button.close').click(function () {
                  $(theModal + ' iframe').attr('src', videoSRC);
              });
          });
      }
  </script>

  </body>
</html>

app/views/seat_reservation/login.html.erb
<div class="jumbotron">
  <div class="container">
      <div class="row">
        <div class="col-md-12">
            <h1 class="text-center">Under Development</h1>
            <br/>
            <br/>
            <p class="text-center"><a class="btn btn-primary btn-lg" href="mailto:abratten@mac.com" role="button">Contact Us</a></p>
        </div>
      </div>
  </div>
</div>
<div class="container">
    <div class="row">
      <div class="col-md-12">
          <%= image_tag('dashboard2.jpg', :class => 'img-responsive block-center') %>
      </div>
    </div>
</div>

app/views/welcome/_sidenav.html.erb
<ul class="nav nav-stacked" id="sidebar">

  <li><%= link_to 'Institutional Partners', institutional_partners_path %></li>
  <li><%= link_to 'Custom Products', custom_products_path %></li>
  <li><%= link_to 'FX Products', fx_products_path %></li>
  <li><%= link_to 'Corporate Ethics', corporate_ethics_path %></li>
  <li><%= link_to 'Intro to PI', intro_to_pi_path %></li>
</ul>

app/views/welcome/corporate_ethics.html.erb
<div class="col-md-9" id="mainCol">
	<br>
	<h2 id="sec3">Corporate Ethics</h2>

	<hr class="col-md-12">
		<p>Our focus is on the client. We didn’t want our powerful tools to be used in generating static fees regardless of performance. Regardless of the product we are creating, our focus has always been on the success of the retail client and their gains. </p>
    <hr class="col-md-12">
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
</div>

app/views/welcome/custom_products.html.erb
<div class="col-md-9" id="mainCol">
	<br>
	<h2 id="sec1">Custom Products</h2>


    <hr class="col-md-12">
    	<p>We have always thrived in providing a modest solution to specific markets, but due to high demand we understand that not all products are benefitted by our dedicated solutions. For an additional fee we can put together solutions for less used products.</p>
    <hr class="col-md-12">
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
</div>

app/views/welcome/fx_products.html.erb
<div class="col-md-9" id="mainCol">
	<br/>
	<h2 id="sec2">FX products</h2>

	<hr class="col-md-12">
		<p>Why do we focus on FX?  When the market crashed in 4Q 2008, we launched our first successful version and recorded a 550% return on variety cap portfolios. The reason we made the decision to target the forex market is due to its high volatility, unpredictability and we wanted to demonstrate our superior algorithm based PI in the harshest environment.</p>
	    <br/>
	    <a href="#">[link] to 2008 October system performance track record available on request*</a>
	    <p>*there were a few private funds which allows the company to disclose under any compliance</p>
	    <p>Since 2008, we have launched V3, the most all-around profit generating model. Due to such high volume capabilities, this product is available to pre-approved and confirmed clients.</p>
    <hr class="col-md-12">
</div>

app/views/welcome/how_it_works.html.erb
<h1>Welcome#how_it_works</h1>
<p>Find me in app/views/welcome/how_it_works.html.erb</p>

app/views/welcome/index.html.erb
<section id="video-hero">
    <div class="container">
        <div class="row">
            <h1 class="text-center vinqulo-title">Vinqulo investment analysis software.</h1>
            <!-- <h2 class="text-center vinqulo-title">Learn more about us.</h2> -->
            <!-- <p class="col-md-8 col-md-offset-2 text-center vinqulo-paragraph">Etsy austin selfies, wolf 3 wolf moon portland actually franzen dreamcatcher fashion axe squid hashtag twee raw denim.</p> -->

            <div  class="video" >





                <!-- <a class="venobox play_btn" data-autoplay="true" data-type="youtube" href="http://youtu.be/LBI2iyLr9zE">
                    <i class="fa fa-play-circle fa-5x" aria-hidden="true"></i>
                </a> -->
                <div class="placeholder">
                    <div id="youtube-video"></div>

                        <!-- <div class="col-xs-12 col-md-push-5" style="padding-top: 250px;color: #fff;padding-left: 50px;">

                        </div> -->

                </div>
            </div>
        </div>
    </div>
</section>


<section id="section_1">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 vinqulo-intro-body">
                <h2 class="text-center">Vinqulo has been a leader in investment analysis software since 2005.</h2>
                <p class="text-center">Since 2005 there have been 3 successful versions to handle different market needs. The latest V3 AI platform features a static spread, high frequency absolute return Fx solution. (Version 3.0)</p>
            </div>
            <div class="col-md-6 col-md-offset-3">
                <hr>
            </div>
            <!-- <div class="col-md-8 col-md-offset-2 testimonial">
                <div class="face-cont col-sm-2 hidden-xs">
                    <span class="face face2"></span>
                </div>
                <blockquote class="col-sm-10">
                    <p>
                        Butcher beard gentrify, taxidermy literally kitsch XOXO vice. Venmo vice craft beer direct trade, readymade 8-bit actually synth mixtape.
                    </p>
                    <cite>Don Hutchings, Investor</cite>
                </blockquote>
            </div> -->
        </div>
    </div>
</div>

<section id="promo">
    <div class="container">
        <h3 class="col-md-6 col-md-push-1">Reserve your seat to get the software today.</h3>
        <div class="col-md-4 col-md-push-1">
            <%= link_to 'RESERVE YOUR SEAT', login_path, :class => 'fbtn btn-flat btn-promo btn-promo-track' %>
            <!-- <a href="#" class="fbtn btn-flat btn-promo btn-promo-track">RESERVE YOUR SEAT</a> -->
        </div>
    </div>
</section>

<section id="steps">
    <div class="container">
        <h2 class="text-center col-xs-12">how it works</h2>
        <p class="text-center col-xs-12">Here’s how it’s done:</p>

        <!-- <div class="explain-block">
            <span class="romb_icon">1</span>
            <h3>create a free account in 20 seconds</h3>
            <p>No approval process, no forms to fill, no phone calls to make and no obligation.</p>
            <hr>
        </div>
        <div class="explain-block">
            <span class="romb_icon">2</span>
            <h3>create a free account in 20 seconds</h3>
            <p>No approval process, no forms to fill, no phone calls to make and no obligation.</p>
            <hr>
        </div>
        <div class="explain-block">
            <span class="romb_icon">3</span>
            <h3>create a free account in 20 seconds</h3>
            <p>No approval process, no forms to fill, no phone calls to make and no obligation.</p>
            <hr>
        </div>
        <div class="explain-block">
            <span class="romb_icon">4</span>
            <h3>create a free account in 20 seconds</h3>
            <p>No approval process, no forms to fill, no phone calls to make and no obligation.</p>
            <button class="get_started fbtn blue">try it now. risk free</button>
        </div> -->
    </div>
</section>

app/views/welcome/institutional_partners.erb
<div class="col-md-9" id="mainCol">
	<br>
	<h2 id="sec0">Institutional Partners</h2>
    <p>Over the years we have been able to successfully service our partners with the following software solutions.</p>

    	<hr class="col-md-12">
    	<p>V1  - This is the version where it all started when we introduced many (functional / operational / viable / executable) risk management charts to our RFED partners and Introductory Brokers using 2-min, 15-min, 30-min, 1-hour and 1-day charts. These were done for all products including equities, bonds, mutual funds, currency, and derivative products.</p>
    <p>V2 - Version 2 utilized the same charting system as Version 1, but not gave entry and exit positions on the charts and you could play or not play them based on the chart in front of you. </p>
    <p>V3 - The latest version of our software is where our partners are enjoying fully automated trading solutions to benefit the (inexperienced / non-professional / unskilled) clients in account volume activity to benefit both them and us. </p>
    <hr class="col-md-12">
	<br>
	<br>
	<br>
	<br>
</div>

app/views/welcome/intro_to_pi.html.erb
<div class="col-md-9" id="mainCol">
    <br>
    <h2 id="sec4">Intro to PI</h2>

    <hr class="col-md-12">
        <p>PI is our main software program that executes the trades for our clients based on a daily calibration. The PI’s main job is to perform multiple stages of data integrity checks and execute trades accordingly.</p>
        <br/>
        <p>At the end of a trading day information from PI is handed over to SI and 26,000+ scenarios are crunched, analyzed and calibrated and given to AI. AI then performs an analysis on the best fits and puts the optimal settings back into PI for the following trading period. </p>
    <hr class="col-md-12">
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
</div>